config/routes.rb
Rails.application.routes.draw do

  root 'rooms#index'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :rooms do
    resources :messages
  end
  resources :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user,dependent: :destroy
  belongs_to :room,dependent: :destroy
  # has_paper_trail
  after_create_commit { broadcast_append_to self.room }
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  has_many :messages,dependent: :destroy
  # has_paper_trail
  scope :public_rooms, -> { where(is_private: false) }
  after_create_commit {broadcast_append_to "rooms"}
end

app/models/user.rb
class User < ApplicationRecord
  # validates_uniqueness_of :username
  has_many :messages,dependent: :destroy
  # has_paper_trail
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user
def current_user
  if session[:user_id]
    @current_user  = User.find(session[:user_id])
  end
end

def log_in(user)
  session[:user_id] = user.id
  @current_user = user
  redirect_to root_path
end

def logged_in?
  !current_user.nil?
end

def log_out
  session.delete(:user_id)
  @current_user = nil
end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def create
      @current_user = current_user
      @message = @current_user.messages.create(content: msg_params[:content], room_id: params[:room_id])
    end

    private
  
    def msg_params
      params.require(:message).permit(:content)
    end
  end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @current_user = current_user unless current_user.present?
    redirect_to '/signin' unless @current_user
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user) unless @current_user
  end

  def create
    @room = Room.create(name: params[:room][:name], is_private: params[:room][:type])
  end

  def show
    @message = Message.new
    @current_user = current_user
    @single_room = Room.find(params[:id])
    @messages = @single_room.messages
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
    render "index"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
      user = User.find_by(password: params[:session][:password],email: params[:session][:email])
      if user
        log_in(user)
      else
        render 'new'
      end
    end
    
  
    def destroy
      log_out if logged_in?
      redirect_to root_path
    end
  
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user=User.new(user_params)
    if @user.save
     redirect_to signin_path
    end
  end

  def new
    @user=User.new
  end

  def index
  end
  private

  def user_params
    params.require(:user).permit(:username,:email,:password,:age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room ,@message], remote: true, class: "d-flex" ) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.submit data: { disable_with: false }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "d-flex" ) do |f| %>
  <%= f.label :RoomName %>
  <%= f.text_field :name, class: "form-control", autocomplete: 'off' %>
    <%= f.label :type %>
    <%= f.text_field :type, class: "form-control", autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatroom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>
<style>
  <%= ".msg-#{current_user&.id}" %> {
  background-color: #007bff !important;
  padding: 10px;
  }
  <%= ".cont-#{current_user&.id}" %> {
  display: flex;
  justify-content: flex-end
  }
</style>
  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %>">
  <div class="message-box msg-<%= message.user.id %> " >
    <% unless message.room.is_private %>
      <h6 class="name"> <%= message.user.username %> </h6>
    <% end %>
  <%= message.content %>
  </div>
</div>

app/views/rooms/_room.html.erb
<div> <%= link_to room.name, room %> </div>

app/views/rooms/index.html.erb
<div id="chatroom_container" class="row bg-dark text-light">
<div id="side_panel" class="col-md-4 col-sm-4">
<h5><%=current_user.username%></h5>
<h4>Users</h4>
 <div>
      <%= turbo_stream_from "users" %>
      <div id="users">
       <% if @users.present? %>
        <%= render @users %>
        <%end%>
      </div>
</div>
 <h4> Rooms </h4>
    <%= render partial: "layouts/new_room_form" %>
    <div>
      <%= turbo_stream_from "rooms" %>
      <div id="rooms">
       <%if @rooms.present?%>
        <%= render @rooms %>
        <%end%>
      </div>
    </div>
  </div>
<div id="room_container"
class="col-md-8 col-sm-8 bg-dark text-light">
<% if @single_room %>
    <h4 class="text-center"> <%= @user&.username || @single_room.name %> </h4>
    <%= turbo_stream_from @single_room %>
    <div id="messages">
    </div>
    <%= render 'layouts/new_message_form'%>
  <% end %>
</div>
</div>

app/views/users/_user.html.erb
<div> <%= link_to user.username, user %> </div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= link_to "Sign In", signin_path %>
<%= link_to "Sign Up", new_user_path %>

app/views/users/new.html.erb
<%= form_with(model:@user) do |f| %>
  <%= f.label :username, 'Enter your name' %>
  <%= f.text_field :username, autocomplete: 'off' %>
  <br>
  <%= f.label :email, 'Enter your email' %>
  <%= f.text_field :email, autocomplete: 'off' %>
  <br>
  <%= f.label :password, 'Enter your password' %>
  <%= f.text_field :password, autocomplete: 'off' %>
  <br>
  <%= f.label :age, 'Enter your age' %>
  <%= f.text_field :age, autocomplete: 'off' %>
  <br>
  <%= f.submit 'SignUp' %>
<% end %>